// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  DB: D1Database
  WORKER_ENV: string
  OPENER_ROUTER_API_KEY: string
}
